name: flutter_project
description: "Premium Flutter Web Portfolio - Divya Dholariya"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  responsive_framework: ^1.5.1
  animated_text_kit: ^4.2.3
  visibility_detector: ^0.4.0+2
  pdf: ^3.11.3
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/resume/
